/*import java.util.Scanner;
public class trycatchblock {
    public static void main(String[] args) {
        Scanner sc=new Scanner(System.in);
       System.out.println("enter no a");
        int a=sc.nextInt();
        System.out.println("enter no2");
        int b=sc.nextInt();
        try{
            int c=a/b;
            System.out.println(c);
        }
        catch(Exception e)
        {
            System.out.println("we failerd to divide because you enter invalid no");
            System.out.println(e);
        }
    }
    
}*/
/*import java.util.Scanner;
 public class trycatchblock{
     public static void main(String[]args) throws Exception
     {
         int[]marks=new int[3];
         marks[0]=89;
         marks[1]=99;
         marks[3]=6;
         Scanner sc=new Scanner(System.in);
         System.out.println("enter the array index");
         int ind=sc.nextInt();
         System.out.println("enter the no use want to divide the value with");
        int number=sc.nextInt();
        try{
            System.out.println("the value at array index entereed is:"+marks[ind]);
            System.out.println("the array valur /no is"+marks[ind]/number);
        }
        catch(Exception e)
        {
         
        System.out.println("some exception occured");   
        System.out.println(e);
        }
      
     }
 }*/
 